### ISSUE TITLE
你好，数据表怎么建，能告诉我一下吗？谢谢

### ISSUE THREAD

**Issue by nasasky** [GzhiYi/accounting-together#13]

**Comment by GzhiYi** [comment]
@nasasky 
可建集合名：bill、bill-group、bill-project、bill-word、feedback、group、project、update-log、user、user-group。
云函数在调用的时候应该会往上面集合（表）进行增删改查。
如果还不行，可以提供错误信息我看看。
![微信截图_20190420094057](https://user-images.githubusercontent.com/21136420/56449787-d561ca00-6350-11e9-8b61-74f67313f8e0.png)
